import JSZip from 'jszip';

export class ScriptGenerator {
    static generatePython(directories, files, rootDir = '') {
        const prefix = rootDir ? `${rootDir}/` : '';
        let script = `import os\n\n# Create directory structure\n# Generated by Directory Tree Generator\n\n`;

        // Create directories first
        if (directories.length > 0) {
            script += `# Create directories\n`;
            directories.forEach(dir => {
                const fullPath = `${prefix}${dir}`.replace(/\/+/g, '/');
                script += `os.makedirs('${fullPath}', exist_ok=True)\n`;
            });
            script += `\n`;
        }

        // Create files
        if (files.length > 0) {
            script += `# Create files\n`;
            files.forEach(file => {
                const filePath = typeof file === 'object' ? file.path : file;
                const content = typeof file === 'object' ? file.content : '';
                const fullPath = `${prefix}${filePath}`.replace(/\/+/g, '/');

                if (content) {
                    const escapedContent = content.replace(/'/g, "\\'");
                    script += `with open('${fullPath}', 'w') as f:\n    f.write('${escapedContent}')\n`;
                } else {
                    script += `with open('${fullPath}', 'w') as f:\n    pass  # Empty file\n`;
                }
            });
        }

        script += `\nprint("Directory structure created successfully!")\n`;
        return script;
    }

    static generateBash(directories, files, rootDir = '') {
        const prefix = rootDir ? `${rootDir}/` : '';
        let script = `#!/bin/bash\n# Create directory structure\n# Generated by Directory Tree Generator\n\n`;

        script += `set -e\necho "Creating directory structure..."\n\n`;

        // Create directories first
        if (directories.length > 0) {
            script += `# Create directories\n`;
            directories.forEach(dir => {
                const fullPath = `${prefix}${dir}`.replace(/\/+/g, '/');
                script += `mkdir -p "${fullPath}"\n`;
            });
            script += `\n`;
        }

        // Create files
        if (files.length > 0) {
            script += `# Create files\n`;
            files.forEach(file => {
                const filePath = typeof file === 'object' ? file.path : file;
                const content = typeof file === 'object' ? file.content : '';
                const fullPath = `${prefix}${filePath}`.replace(/\/+/g, '/');

                if (content) {
                    script += `echo "${content.replace(/"/g, '\\"')}" > "${fullPath}"\n`;
                } else {
                    script += `touch "${fullPath}"\n`;
                }
            });
        }

        script += `\necho "Directory structure created successfully!"\n`;
        return script;
    }

    static generateWindows(directories, files, rootDir = '') {
        const prefix = rootDir ? `${rootDir}\\` : '';
        let script = `@echo off\nREM Create directory structure\nREM Generated by Directory Tree Generator\n\n`;

        script += `echo Creating directory structure...\n\n`;

        // Create directories first
        if (directories.length > 0) {
            script += `REM Create directories\n`;
            directories.forEach(dir => {
                const fullPath = `${prefix}${dir}`.replace(/\//g, '\\').replace(/\\+/g, '\\');
                script += `if not exist "${fullPath}" mkdir "${fullPath}"\n`;
            });
            script += `\n`;
        }

        // Create files
        if (files.length > 0) {
            script += `REM Create files\n`;
            files.forEach(file => {
                const filePath = typeof file === 'object' ? file.path : file;
                const content = typeof file === 'object' ? file.content : '';
                const fullPath = `${prefix}${filePath}`.replace(/\//g, '\\').replace(/\\+/g, '\\');

                if (content) {
                    script += `echo ${content.replace(/>/g, '^>')} > "${fullPath}"\n`;
                } else {
                    script += `if not exist "${fullPath}" type nul > "${fullPath}"\n`;
                }
            });
        }

        script += `\necho Directory structure created successfully!\npause\n`;
        return script;
    }

    static generatePowerShell(directories, files, rootDir = '') {
        const prefix = rootDir ? `${rootDir}\\` : '';
        let script = `# Create directory structure\n# Generated by Directory Tree Generator\n\n`;

        script += `Write-Host "Creating directory structure..."\n\n`;

        // Create directories first
        if (directories.length > 0) {
            script += `# Create directories\n`;
            directories.forEach(dir => {
                const fullPath = `${prefix}${dir}`.replace(/\//g, '\\').replace(/\\+/g, '\\');
                script += `if (!(Test-Path -Path "${fullPath}")) { New-Item -ItemType Directory -Force -Path "${fullPath}" }\n`;
            });
            script += `\n`;
        }

        // Create files
        if (files.length > 0) {
            script += `# Create files\n`;
            files.forEach(file => {
                const filePath = typeof file === 'object' ? file.path : file;
                const content = typeof file === 'object' ? file.content : '';
                const fullPath = `${prefix}${filePath}`.replace(/\//g, '\\').replace(/\\+/g, '\\');

                if (content) {
                    const escapedContent = content.replace(/"/g, '`"');
                    script += `if (!(Test-Path -Path "${fullPath}")) { Set-Content -Path "${fullPath}" -Value "${escapedContent}" }\n`;
                } else {
                    script += `if (!(Test-Path -Path "${fullPath}")) { New-Item -ItemType File -Force -Path "${fullPath}" }\n`;
                }
            });
        }

        script += `\nWrite-Host "Directory structure created successfully!"\n`;
        return script;
    }

    static generateNodeJS(directories, files, rootDir = '') {
        const prefix = rootDir ? `${rootDir}/` : '';
        let script = `const fs = require('fs');\nconst path = require('path');\n\nconsole.log("Creating directory structure...");\n\n`;

        script += `const directories = [\n`;
        directories.forEach(dir => {
            const fullPath = `${prefix}${dir}`.replace(/\/+/g, '/');
            script += `    '${fullPath}',\n`;
        });
        script += `];\n\nconst files = [\n`;
        files.forEach(file => {
            const filePath = typeof file === 'object' ? file.path : file;
            let content = typeof file === 'object' ? file.content : '';
            content = content.replace(/\\n/g, '\n'); // Unescape newlines
            const fullPath = `${prefix}${filePath}`.replace(/\/+/g, '/');
            script += `    { path: '${fullPath}', content: '${content.replace(/'/g, "\\'")}' },\n`;
        });
        script += `];\n\n`;

        script += `// Create directories\ndirectories.forEach(dir => {\n    fs.mkdirSync(dir, { recursive: true });\n});\n\n`;
        script += `// Create files\nfiles.forEach(file => {\n    if (!fs.existsSync(file.path)) {\n        fs.writeFileSync(file.path, file.content || '');\n    }\n});\n\n`;
        script += `console.log("Directory structure created successfully!");\n`;

        return script;
    }

    static async generateZip(directories, files, rootDir = '') {
        const zip = new JSZip();
        const root = rootDir ? zip.folder(rootDir) : zip;

        // Create directories
        directories.forEach(dir => {
            root.folder(dir);
        });

        // Create files
        files.forEach(file => {
            const content = typeof file === 'object' ? (file.content || '').replace(/\\n/g, '\n') : '';
            const filePath = typeof file === 'object' ? file.path : file;
            root.file(filePath, content);
        });

        return await zip.generateAsync({ type: 'blob' });
    }

    static generateAIPrompt(structure, rootDir = 'project') {
        let prompt = `I am working on a project named "${rootDir}". Here is the intended directory structure:\n\n`;

        prompt += '```\n';
        structure.forEach(node => {
            const indent = '  '.repeat(node.level);
            const prefix = node.isFile ? '📄 ' : '📁 ';
            prompt += `${indent}${prefix}${node.name}\n`;
        });
        prompt += '```\n\n';

        prompt += `Please help me initialize this project. The root directory should be "${rootDir}".`;
        return prompt;
    }
}
